### ISSUE TITLE
Не высылайте приглашение, если не сделали задачу

### ISSUE THREAD

**Issue by coursar** [AlekseiILitvinov/Week3HomeworkQueueService#3]

**Comment by AlekseiILitvinov** [comment]
Простите, возможно я что-то не так понял про pull requests. Я сделал ветку dev и создал пул реквест. Или нужно было по старому сделать всё в master и сдавать через issue?

**Comment by coursar** [comment]
Пока по старому )) мы же не прошли пулл-реквесты
